[2024-09-20T00:04:52.151+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T00:04:52.157+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-20T00:04:52.160+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-20T00:04:52.160+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-20T00:04:52.165+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-09-19 00:00:00+00:00
[2024-09-20T00:04:52.168+0000] {standard_task_runner.py:72} INFO - Started process 295 to run task
[2024-09-20T00:04:52.171+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-09-19T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpqixzh7lv']
[2024-09-20T00:04:52.172+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask s3_upload
[2024-09-20T00:04:52.193+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-19T00:00:00+00:00 [running]> on host d52e67a52229
[2024-09-20T00:04:52.221+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kittaya' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-19T00:00:00+00:00'
[2024-09-20T00:04:52.222+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T00:04:53.369+0000] {logging_mixin.py:190} INFO - The AWS Access Key Id you provided does not exist in our records.
[2024-09-20T00:04:53.437+0000] {logging_mixin.py:190} INFO - Error uploading file to S3: The AWS Access Key Id you provided does not exist in our records.
[2024-09-20T00:04:53.438+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-20T00:04:53.449+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T00:04:53.449+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=scheduled__2024-09-19T00:00:00+00:00, execution_date=20240919T000000, start_date=20240920T000452, end_date=20240920T000453
[2024-09-20T00:04:53.477+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-20T00:04:53.489+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T00:04:53.490+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
