[2024-09-10T00:04:13.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T00:04:13.044+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-10T00:04:13.047+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-09-10T00:04:13.047+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-10T00:04:13.051+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-09-09 00:00:00+00:00
[2024-09-10T00:04:13.053+0000] {standard_task_runner.py:72} INFO - Started process 175 to run task
[2024-09-10T00:04:13.055+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpqgr77j94']
[2024-09-10T00:04:13.056+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask reddit_extraction
[2024-09-10T00:04:13.074+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction scheduled__2024-09-09T00:00:00+00:00 [running]> on host d52e67a52229
[2024-09-10T00:04:13.100+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kittaya' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-09-10T00:04:13.100+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T00:04:13.118+0000] {logging_mixin.py:190} INFO - connected to reddit!
[2024-09-10T00:04:13.121+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'www.reddit.com\', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff878ee950>: Failed to resolve \'www.reddit.com\' ([Errno -2] Name or service not known)"))')) status: GET https://oauth.reddit.com/r/dataengineering/top
[2024-09-10T00:04:13.792+0000] {sessions.py:161} WARNING - Retrying due to ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'www.reddit.com\', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff878ee4d0>: Failed to resolve \'www.reddit.com\' ([Errno -2] Name or service not known)"))')) status: GET https://oauth.reddit.com/r/dataengineering/top
[2024-09-10T00:04:17.247+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 11, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 29, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 51, in _post
    response = self._requestor.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff878e4b80>: Failed to resolve 'www.reddit.com' ([Errno -2] Name or service not known)"))
[2024-09-10T00:04:17.259+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20240910T000413, end_date=20240910T000417
[2024-09-10T00:04:17.265+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T00:04:17.265+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task reddit_extraction (error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff878e4b80>: Failed to resolve 'www.reddit.com' ([Errno -2] Name or service not known)")); 175)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 11, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 29, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 254, in _request_with_retries
    return self._do_retry(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/auth.py", line 51, in _post
    response = self._requestor.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/prawcore/requestor.py", line 70, in request
    raise RequestException(exc, args, kwargs) from None
prawcore.exceptions.RequestException: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff878e4b80>: Failed to resolve 'www.reddit.com' ([Errno -2] Name or service not known)"))
[2024-09-10T00:04:17.285+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-10T00:04:17.300+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T00:04:17.302+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
