[2024-09-17T00:00:03.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T00:00:03.773+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-17T00:00:03.775+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-09-17T00:00:03.775+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-17T00:00:03.780+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-09-16 00:00:00+00:00
[2024-09-17T00:00:03.782+0000] {standard_task_runner.py:72} INFO - Started process 265 to run task
[2024-09-17T00:00:03.784+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'scheduled__2024-09-16T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpk3qwc62o']
[2024-09-17T00:00:03.785+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask s3_upload
[2024-09-17T00:00:03.801+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload scheduled__2024-09-16T00:00:00+00:00 [running]> on host d52e67a52229
[2024-09-17T00:00:03.825+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kittaya' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-16T00:00:00+00:00'
[2024-09-17T00:00:03.826+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T00:00:04.567+0000] {logging_mixin.py:190} INFO - The AWS Access Key Id you provided does not exist in our records.
[2024-09-17T00:00:04.632+0000] {logging_mixin.py:190} INFO - Error uploading file to S3: The AWS Access Key Id you provided does not exist in our records.
[2024-09-17T00:00:04.633+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T00:00:04.638+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T00:00:04.638+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=scheduled__2024-09-16T00:00:00+00:00, execution_date=20240916T000000, start_date=20240917T000003, end_date=20240917T000004
[2024-09-17T00:00:04.649+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-17T00:00:04.658+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T00:00:04.658+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
